### ISSUE TITLE
Error at checkout

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#2171] opened 2020-10-30 12:39 UTC
https://www.screencast.com/t/8YnYtGux5

[Details in the slack thread](https://rise-vision-inc.slack.com/archives/CCELMSZFZ/p1604057191154700)

**Comment by alex-deaconu** [comment] 2020-11-02 16:35
@sheadarlison as per investigation, this was caused by a backend error from contacting a 3rd party API. However, due to the latency of the call (60s) you did not see the error, or an indication that something was still in progress. We have fixed an issue which was causing a spinner not to show while contacting that API, which should now clearly indicate that something's still in progress. Closing. Thanks!

**Closed by alex-deaconu** 2020-11-02 16:35 UTC
