### ISSUE TITLE
Monitoring Timeline not respecting changes

### ISSUE THREAD

**Issue by alanclayton** [Rise-Vision/rise-vision-apps#585] opened 2018-03-13 17:12 UTC
I'm unable to change the Monitoring Timeline start/end time to be anything other than 3:00am - 12:30pm. 

1. Uncheck `Always`
2. Edit Timeline
3. Uncheck `All Day`
4. Change `Start Time` to be 8:00 AM then Apply
5. `Start Time` should be shown as 8:00 AM, but instead appearing as 3:00 AM  https://www.screencast.com/t/EaOmf57v

**Comment by fjvallarino** [comment] 2018-03-13 19:11
@alanclayton I'm closing this issue as discussed, since it can't be reproduced currently.

**Closed by fjvallarino** 2018-03-13 19:11 UTC
