### ISSUE TITLE
Not remembering the sub company

### ISSUE THREAD

**Issue by rjcahoy** [Rise-Vision/rise-vision-apps#88] opened 2016-02-18 18:22 UTC
I noticed that recently when navigating to a sub company then switching apps (from say displays to schedules) will kick you out of the sub company and back to the top level company.

Specific steps to recreate:

- go to sub company Plexpod (https://apps.risevision.com/displays/list?cid=ea4e38ec-b3b1-4362-9877-40c6862ce915)
- go to displays and open any display and try to hit reboot player or save or anything
- then navigate to schedules (top navigation or app navigator)

it will then kick you out of the sub company and to the top level company (in my case Rise Vision)

**Comment by ezequielc** [comment] 2016-02-18 18:33
@rjcahoy I think this issue is a duplicate of https://github.com/Rise-Vision/rise-vision-apps/issues/68
Do you agree? Thanks

**Comment by ByronDarlison** [comment] 2016-02-18 20:01
@ezequielc I think it is. Do we have a trello card open for 68 anywhere? Thanks

**Comment by ezequielc** [comment] 2016-02-18 20:48
@ByronDarlison Yes, we have: https://trello.com/c/E3aDZvdr/1135-issue-68-user-gets-booted-back-to-master-company-after-clicking-save-on-display-page-1 . Cheers

**Comment by ByronDarlison** [comment] 2016-02-18 21:28
Thanks! Do you think we should move this up to our current backlog? Thanks!

**Comment by ezequielc** [comment] 2016-02-18 21:33
@ByronDarlison Yes, I will move it to our Sprint backlog. Should we close this issue and leave only #68 open? Thanks

**Comment by ByronDarlison** [comment] 2016-02-18 21:35
Thanks! And yes, let's just keep one issue open. Thanks

**Comment by ezequielc** [comment] 2016-02-18 21:38
@rjcahoy I am closing this issue as it is a duplicate of #68 . Thanks!

**Closed by ezequielc** 2016-02-18 21:38 UTC
