### ISSUE TITLE
Certain Schedules containing HTML Templates show preview button

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#1180] opened 2019-08-13 20:43 UTC
**Expected Behavior**
When users open a Schedule a preview button shouldn't be there if an HTML Template is in the Schedule playlist. 

**Actual Behavior** 
Opening certain Schedules containing HTML Templates still shows the preview button. Clicking preview shows a grey loading circle screen indefinitely.

**Steps to reproduce:**
So far it only happens under one specific Schedule.
Not reproducible otherwise.

**Comment by sheadarlison** [comment] 2019-08-13 20:46
[Relevant thread](https://rise-vision-inc.slack.com/archives/CCDCUDRJQ/p1565727073403900)

**Comment by fjvallarino** [comment] 2019-09-05 14:24
@kaden-rise @sheadarlison @stulees I have not been able to reproduce this problem, as mentioned in the issue description and associated Slack thread. 

In my opinion, the cause for this situation could be:

- A new template was added to Product's spreadsheet with missing `category` and was published.
- A new Presentation was created with that _invalid_ template.
- The template definition in Product's spreadsheet was fixed and re-published.

That would explain why we don't see this situation happening for other users/presentations.

If you are ok with this, I will close the issue.

**Comment by stulees** [comment] 2019-09-05 14:55
@fjvallarino Good with me 👍

**Closed** 2019-09-05 14:56 UTC
