### ISSUE TITLE
/USDISC=, /CAPRIME=, /USPRIME= do not appear in the Editor

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1206] opened 2019-08-21 20:09 UTC
### What is the expected behavior?
/USDISC=, /CAPRIME=,/USPRIME= are in the default list in the Rates & Indicators table and should be selectable in editor.

### What is the actual behavior?
/USDISC=,/CAPRIME=,/USPRIME= are in the default list, but they disappear when you click "Edit" on the Financial Table component and cannot be found in Search to be re-added.

### What steps can be taken to replicate the problem?
1. Create a fresh copy of the Rates & Indicators Full Screen template.
2. Make note of the default list in the preview, especially at the top.
3. Click on "Edit" next to the Financial component.
4. Make note of the changes in the preview.  /USDISC=, /CAPRIME= and /USPRIME= are missing.
5. Click on "Add Market Statistics".
6. Search for /USDISC=, /CAPRIME= or /USPRIME=

**Comment by stulees** [comment] 2019-09-03 20:41
@mmeiers @pcsandford I've investigated this and I'm wondering why the `/` character is necessary for the symbols mentioned above in the description of this issue - see the code [here](https://github.com/Rise-Vision/html-template-library/blob/master/single-rates-indicators/src/template.html#L75).

I tried searching `USDISC=` for example and it returns correctly. I think the fix for this is to remove those `/` characters. Thoughts? If you agree, I think it makes sense for you to take ownership of the defect (also cause the template needs upgrading to use v2 of financial component).

**Comment by stulees** [comment] 2019-09-03 20:59
@mmeiers @pcsandford After more experimenting, I see now the items listed popular results have symbols with code values starting with `/` and after selecting one, it's properly added to the list, saved, and correctly appears when reopening the presentation. So there may be an issue somewhere in the initialization of this template via blueprint _or_ searching these symbols using `/` character. I'll look into it further.

**Comment by pcsandford** [comment] 2019-09-03 22:11
@stulees ok thanks! If the solution is to take out those / values from the selector let me know and I will remove them from the default list too. Thanks!

**Comment by stulees** [comment] 2019-09-04 15:13
@alexey-rise @tejohnso In investigating this I've found the root problem is with the Financial Server. If you make a request to the API for common instruments based on _Market Statistics_ category, there are items returned that have symbol value starting with `/` character, specifically the instruments mentioned in the description of this issue - `/USDISC=`, `/CAPRIME=` and `/USPRIME=`. 

https://contentfinancial2.appspot.com/_ah/api/financial/v1.00/instruments/common?category=Market%20Statistics

The problem is, when making a request to the API to query one of those instruments based on symbol value, empty data is returned:

https://contentfinancial2.appspot.com/_ah/api/financial/v1.00/instrument/search?category=Market%20Statistics&query=/USDISC=

When you query another item that doesn't include the `/`, results are returned as expected:

https://contentfinancial2.appspot.com/_ah/api/financial/v1.00/instrument/search?category=Market%20Statistics&query=USJOBN=ECI

Let me know if this is clear and if you agree that this issue is with the Financial Server. If so, can you take ownership of this issue?

**Comment by alexey-rise** [comment] 2019-09-04 16:34
@stulees issue created for Financial Server: https://github.com/Rise-Vision/contentfinancial2/issues/93

**Comment by santiagonoguez** [comment] 2019-09-04 16:39
@stulees BTW, for the query to succeed, slashes should be URL encoded, as they have special meaning in URLs. It doesn't seem to work even if encoded, though. I'm not sure if editor should take this into account once it's fixed on the server side.

**Comment by stulees** [comment] 2019-09-04 16:48
@santiagonoguez It's not necessarily required of Editor to do that for the API call. I think we should close this for now and wait until financial server issue is resolved. 

@PatrickA-RiseVision @mmeiers @pcsandford FYI, I'm closing this issue as the bug is with Financial Server and there is a new issue open for that - https://github.com/Rise-Vision/contentfinancial2/issues/93 .

**Closed by stulees** 2019-09-04 16:48 UTC
Labels: bug

**Comment by stulees** [comment] 2019-09-04 20:43
@PatrickA-RiseVision FYI, the fix has been deployed to financial server and I validated this is now working properly. Let me know if you experience otherwise, thanks. @santiagonoguez FYI
