### ISSUE TITLE
Copying Schedule Items results in the item not moving, and creating blank Schedule items

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/rise-vision-apps#810] opened 2019-01-29 18:06 UTC
### What is the expected behavior?
When you copy a Schedule item, you should be able to move it wherever you want in the Schedule Playlist.

### What is the actual behavior?
When you copy a Schedule Item, and/or create a copy of that copied item, the item does not move where you move it to in the Playlist, and sometimes creates a blank Schedule item where you tried to move it.

### What steps can be taken to replicate the problem?

Follow the steps in this video: https://goo.gl/mCBzXd

**Comment by alex-deaconu** [comment] 2019-01-29 21:13
Duplicate of #807. Closing.

**Closed by alex-deaconu** 2019-01-29 21:13 UTC
Labels: bug
