### ISSUE TITLE
Several presentations were created when editing presentation title

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#1073] opened 2019-06-24 16:49 UTC
A weird behavior presented right after creating a presentation on Samsung Galaxy S8 on browserstack.

Context: the simulation was very slow, and several network errors presented during the test, so it seems that the network of the remote test phone was not very good.

After creating a new presentation of the new QA template, the phone opened it but showed a dialog saying it could not be saved ( network error apparently ).

But as the presentation could open, I tried to edit the presentation title. The editor was presenting weird editing behavior, maybe related to the slow interaction with the remote phone, and/or to https://github.com/Rise-Vision/rise-vision-apps/issues/928

The real crappy behavior was that as a result of trying to edit this, several new presentations were created, apparently by auto-save ( trying to insert the presentation as if it were new, it seems ). Look capture below:

![multiple-creation](https://user-images.githubusercontent.com/33162690/60036996-1db1a700-9676-11e9-8fda-e0d85ecdea72.png)

**Comment by santiagonoguez** [comment] 2019-06-24 17:55
I think the real problem here was that the initial save failed, so every subsequent auto-save did not see a presentation id, and did an insertion instead of an update.

**Comment by andrecardoso** [comment] 2019-07-18 13:08
I couldn't reproduce this issue, neither Francisco (see https://github.com/Rise-Vision/rise-vision-apps/pull/1115#issuecomment-512570617). Closing it.

**Closed by andrecardoso** 2019-07-18 13:08 UTC
