### ISSUE TITLE
Clicking on a Widget in the Presentation Placeholder Playlist in Editor incorrectly redirects to Home

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#802] opened 2019-01-16 20:29 UTC
### What is the expected behavior?
Clicking on a Widget in the Presentation Placeholder Playlist in Editor opens the Widget settings.
### What is the actual behavior?
Clicking on a Widget in the Presentation Placeholder Playlist in Editor redirects to Home, as though the user has just logged in.  If I try this with a sub-company using my Rise Vision administrator account, I end up in the root of Rise.
### What steps can be taken to replicate the problem?
1. Open an affected presentation (?  It may not be per presentation, but I've not been able to replicate it with other presentations yet)
2. Click on a Placeholder
3. Click on an item in the Playlist
4. You are redirected to Home page

**Comment by fjvallarino** [comment] 2019-01-23 19:44
@PatrickA-RiseVision @pcsandford I'm closing this issue, since we have not been able to reproduce it in the Apps team. I did see it happen on Patrick's machine, but I could never replicate it outside that environment. This makes me think it's cache related (I know you mentioned clearing the cache fixed the problem temporarily for some users, but then it came back) but, most importantly, not being able to reproduce it makes it really hard to figure out what the cause could be. In case this is reported again, please re open the issue. Thanks!

**Comment by fjvallarino** [comment] 2019-01-23 19:44
@ezequielc @alex-deaconu FYI

**Comment by PatrickA-RiseVision** [comment] 2019-02-01 19:21
This has been reported again a few times.  I will link specific examples on the card.

**Comment by alex-deaconu** [comment] 2019-02-04 19:16
@PatrickA-RiseVision we have released a fix for this issue. Please let us know if you encounter any more tickets related to this. Thanks!

**Closed by alex-deaconu** 2019-02-04 19:16 UTC
