### ISSUE TITLE
Publishing a presentation to a new schedule does not publish the presentation

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2132] opened 2020-10-19 15:30 UTC
### What is the expected behavior?
Clicking "Publish" on a presentation publishes the latest changes.  I can choose to add it to a schedule if it isn't already in one in the same action.
### What is the actual behavior?
Clicking "Publish" on a presentation that isn't already in a schedule and attempting to add it to a new schedule does not publish the presentation.
### What steps can be taken to replicate the problem?
After clicking "Publish", click "Add Schedule" in the schedule modal.  Here's a video: https://drive.google.com/file/d/1kQVwO3h4RAYI3HPCp6W3VQfy1AgHnNIA/view?usp=drivesdk

**Comment by ezequielc** [comment] 2020-10-19 16:39
@jasoncaldwell I would like to confirm the expected behaviour here. 

As users navigate away to the New Schedule page, they didn't click the Publish button from the confirmation modal, therefore the Presentation is not published:
<img width="230" alt="Screen Shot 2020-10-19 at 1 36 52 PM" src="https://user-images.githubusercontent.com/7738553/96480152-44eb9a80-1210-11eb-97ad-50e0f2a03d21.png">

What do you think the expected flow should be? Should we just go ahead an publish the presentation in this case, as per Patrick's suggestion? Thanks!

**Comment by ByronDarlison** [comment] 2020-10-20 13:27
My two cents, I think we should automatically publish. @jasoncaldwell thoughts? Thanks

**Comment by jasoncaldwell** [comment] 2020-10-20 13:59
@ezequielc @PatrickA-RiseVision @ByronDarlison Agree with Byron. I think that when someone navigates away from [that modal](https://github.com/Rise-Vision/rise-vision-apps/issues/2132#issuecomment-712289397) to add a new schedule, the presentation should be published and automatically added to the target schedule. If someone chooses to delete or cancel the creation of a new schedule, the presentation should still remain published.

I think we can revisit this flow in the future because it's a bit tangled, but it's a good compromise for now. Perhaps we could change the flow such that when someone clicks the "Publish" button in editor, it's published, and then the next modal (what @ezequielc [is showing](https://github.com/Rise-Vision/rise-vision-apps/issues/2132#issuecomment-712289397)) is focused on adding the the presentation to a schedule, if it's not in one already. The CTA for that modal, in that case, should be "Add" not "Publish", because the presentation is already published. That's a cleaner flow in my mind.

**Comment by alex-deaconu** [comment] 2020-10-20 18:44
@ByronDarlison @jasoncaldwell @PatrickA-RiseVision having reviewed the above and the code as well, it seems that the cleaner flow that Jason is proposing above would actually simplify the flow as well as the implementation. With a few tweaks here's what we are proposing:

> When someone clicks the "Publish" button in editor, it's published, and then the next modal is focused on adding the presentation to a schedule, if it's not in one already. They can update the selected Schedules or add a new Schedule in the dropdown. Once they've finished, the single CTA would be a Done button.

<img width="369" alt="Screen Shot 2020-10-20 at 2 40 01 PM" src="https://user-images.githubusercontent.com/6218188/96629905-3a99d100-12e2-11eb-903f-1da0484146a8.png">

Let me know your thoughts. @ezequielc fyi. Thanks!

**Comment by PatrickA-RiseVision** [comment] 2020-10-20 19:45
@alex-deaconu just to confirm, choosing no schedules and clicking "Okay, I'm Done" would still publish and allow them to continue without adding it to a schedule, correct?

**Comment by alex-deaconu** [comment] 2020-10-20 20:13
@PatrickA-RiseVision correct. Actually the Presentation would be Published before the modal even shows up, to avoid any confusion. Thanks.

**Comment by jasoncaldwell** [comment] 2020-10-21 04:38
@alex-deaconu I'd modify the CTA [in your screenshot](https://github.com/Rise-Vision/rise-vision-apps/issues/2132#issuecomment-713063141) to say "Add".

**Comment by alex-deaconu** [comment] 2020-10-21 13:15
@jasoncaldwell sounds good, thanks for the feedback!

**Comment by ezequielc** [comment] 2020-10-22 17:30
Fix has been released as per above. Thanks

**Closed by ezequielc** 2020-10-22 17:30 UTC
