### ISSUE TITLE
Editing a placeholder playlist item prompts users to subscribe to a plan even if their company has a plan

### ISSUE THREAD

**Issue by kaden-rise** [Rise-Vision/rise-vision-apps#871] opened 2019-03-22 21:46 UTC
**Actual Behavior:**
Opening the playlist item settings for a widget requiring a license results in a prompt asking the user to subscribe even though their company has a plan.

**Expected Behavior:**
The playlist item settings should not prompt a user to subscribe if they already have a plan.

**Screenshots:**
![image](https://user-images.githubusercontent.com/33877348/54854576-03ec7680-4cb9-11e9-96a7-dd0b79625e96.png)

**Steps to Reproduce:**
1. Add a Widget requiring a license to a placeholder in a company with an active plan.
2. Open the playlist item settings for the licensed Widget.

**Comment by olegrise** [comment] 2019-04-03 20:41
@kaden-rise I can't reproduce the issue. Do you have a link to this presentation?

**Comment by alex-deaconu** [comment] 2019-04-10 14:08
@kaden-rise a fix for this issue has been deployed. To confirm, if the User has Professional Licenses, the notification will still show but will not have the Subscribe button anymore. Thanks!

**Closed by alex-deaconu** 2019-04-10 14:08 UTC
