### ISSUE TITLE
Purchased licenses are assigned immediately to Sub-Company displays if they were previously licensed

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1547] opened 2020-02-27 22:56 UTC
### What is the expected behavior?
If I purchase a Display License in the parent company for a given Free Display, I can assign it to the Display.

### What is the actual behavior?
If I purchase a Display License in the parent company for a given Free Display, and there are Free Displays in any of the sub-companies which were previously licensed, the License is automatically assigned to that Display without prompting.

### What steps can be taken to replicate the problem?
- Create a company to behave as the parent company, we'll call it "PARENT".
- Create a company under the parent to behave as a sub-company, we'll call it "SUB"
- Add a subscription for any number of licenses in PARENT.
- Add another subscription for any number of licenses in SUB.
- Create Displays so that all the Licenses in PARENT and SUB are in use.
- Cancel the subscription in SUB.
- Create any number of additional Displays in PARENT so that you have Free Displays mixed with Licensed Displays.
- At this point you should have a number of licenses in PARENT which are all in use, some Free Displays in PARENT and a number of Free Displays in SUB.
- Add a Display License to the subscription in PARENT.
- The License will be assigned to one of the Displays in SUB.

Here's a video where I replicate the behavior:
https://drive.google.com/a/risevision.com/file/d/1QVMqdBsVeK9P3S7lHxSV64AWtkOLv-UG/view?usp=drivesdk

**Comment by ezequielc** [comment] 2020-03-02 19:20
@PatrickA-RiseVision Even though it is not always desirable, this is working as designed. As part of closing https://github.com/Rise-Vision/rise-vision-apps/issues/1546, we will be sharing a diagram clarifying the expected flow for auto license assignment.
For now, I will close this as it is a duplicate of https://github.com/Rise-Vision/rise-vision-apps/issues/1546. Thanks

**Closed by ezequielc** 2020-03-02 19:20 UTC
