### ISSUE TITLE
Firefox: Moving playlist items in placeholder get "stuck".

### ISSUE THREAD

**Issue by btfrise** [Rise-Vision/rise-vision-apps#1540] opened 2020-02-26 19:24 UTC
**How to replicate**
In Firefox, open a Presentation
Open a Placeholder with multiple playlist items ([EXAMPLE](https://apps.risevision.com/editor/workspace/4fe271bd-5847-4b66-be2c-782edb1a9427?cid=e113f8d6-de1c-4c26-b160-4ef1c4589957))
Move a playlist item, it may take moving more than one.

**What happens**
Sometimes, and item being moved gets stuck overlapping other playlist items at the bottom of the screen.

**What should happen?**
Playlist items shouldn't get stuck.

[Example Video](https://www.screencast.com/t/YvNQyndiKAfS)

**Comment by btfrise** [comment] 2020-02-26 20:19
Update, this can be reproduced on Chrome and is affecting two users so far.

**Comment by alex-deaconu** [comment] 2020-02-26 20:56
@btfrise this has been fixed. It seems to have been caused by a library update in Apps. We reverted to the previous version and are no longer able to replicate. Closing. Thanks!

**Closed by alex-deaconu** 2020-02-26 20:56 UTC
