### ISSUE TITLE
Copying and dragging Widgets occasionally results in "ghost" placeholders that cannot be interacted with

### ISSUE THREAD

**Issue by colby-maughan** [Rise-Vision/rise-vision-apps#1541] opened 2020-02-26 20:05 UTC
### What is the expected behavior?
User should be able to copy a widget, then move it wherever they want in their placeholder's contents.

### What is the actual behavior?
Placeholder widgets will occasionally just get stuck on the left bar with no way to remove them, regardless of what placeholder you have open on the left bar. Image below shows placeholder and widget on the same bar, which should not be possible.
![image](https://user-images.githubusercontent.com/41346848/75382278-666dcf80-5897-11ea-87fd-8d83d4633026.png)

### What steps can be taken to replicate the problem?
So far, the most reliable way to replicate the issue is to open a placeholder, insert an image widget, then _very_ rapidly click the copy button. Afterwards, try and drag an item and it will freeze and persist on the screen until you reload the page. I wasn't able to replicate 100% of the time, so you may need to try this a few times.

Confirmed to be an issue on Windows, Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by alex-deaconu** [comment] 2020-02-26 20:57
Duplicate of #1540 

This has been fixed. It seems to have been caused by a library update in Apps. We reverted to the previous version and are no longer able to replicate. Closing. Thanks!

**Closed by alex-deaconu** 2020-02-26 20:57 UTC
