### ISSUE TITLE
[App Homepage] "Share Menu" persistent when changing viewport and then click "Share" again

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#1805] opened 2020-06-29 21:02 UTC
**Issue:** "Share Menu" is persistent when I change the viewport to mobile and then click "Share" again. Please see Loom video.

https://www.loom.com/share/3dd78cec57594fe299685a52cf00c88d

**Comment by ezequielc** [comment] 2020-06-30 14:38
@jasoncaldwell What would be the expected behaviour? I am wondering if we should close it when we change the viewport/resize.
The main problem is that the action originated from the mobile Share button, that is no longer visible when we show the desktop version of the popup. Thanks!

**Comment by jasoncaldwell** [comment] 2020-06-30 17:29
@ezequielc For me, the expected behavior would be that the "Share Menu" adapts, whenever the window is resized. Although, it's is easier to simply close it whenever a viewport is changed, I'm okay with that too.

**Comment by ezequielc** [comment] 2020-06-30 17:41
@jasoncaldwell Thanks!

**Closed** 2020-07-02 14:36 UTC
Labels: bug

**Comment by ezequielc** [comment] 2020-07-02 14:58
@jasoncaldwell I ended up picking the simpler option and I am closing the mobile Share menu on resize. 
Also, I couldn't replicate the extra margin that you saw at top on mobile. But I believe it is due to the blue Promotion bar. Once the bar is dismissed, you will no longer see that extra margin. Thanks!
