### ISSUE TITLE
Templates that don't support Play Until Done can be embedded into Templates that are Play Until Done

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#1723] opened 2020-06-09 15:49 UTC
### What is the expected behavior?
Play Until Done is not enabled if the Template cannot be "Done".

### What is the actual behavior?
Play Until Done is enabled on Embedded Templates, even when all the content embedded in them cannot be "Done".

### What steps can be taken to replicate the problem?
1- Create a new presentation from the 2x2 Embedded Zoned template.
2- In one or more of the quadrants, embed a presentation created from the Google Slides template.
3- Add the 2x2 Embedded Zoned presentation to a schedule.

"Play Until Done" is selected by default.

**Comment by ezequielc** [comment] 2020-06-09 16:25
@olegrise fyi. Thanks!

**Comment by olegrise** [comment] 2020-06-09 21:01
@PatrickA-RiseVision I believe there are two ways of implementing PUD (Play Until Done) constraints in a schedule.

**Here is how it's implemented now**
The PUD in a template is either enabled or disable at the moment when template is created by designer. For greater certainty it cannot change dynamically at runtime. When a PUD presentation is added to a schedule, then "Done" option is selected that template. In your the 2x2 Embedded Zoned presentation is PUD presentation and so the "Done" is enabled and selected. Everything is working as expected.

**Here is what you recommend (if I understand you correctly)**
The PUD is determined dynamically based on presentation's content. If there is at least one piece of the content that can trigger "Done" event, then this presentation is PUD.
This approach has multiple drawbacks. 
One of them is that parsing the content of a presentation and especially multiple presentations in case of embedded content would be quite challenging. 
The second problem is that lets say your 2x2 Embedded Zoned presentation embeds a Full Screen Image presentation which is PUD. That allows you to go the schedule and select "Done" option. After that you go the 2x2 Embedded Zoned and replace Full Screen Image with Google Slides. Should all schedules that reference 2x2 Embedded Zoned presentation be automatically updated and "Done" option is unchecked?

**Comment by PatrickA-RiseVision** [comment] 2020-06-09 22:26
@olegrise thanks for the explanation, though I'm not sure I follow the current implementation.

If I understand correctly it's as simple as "the expected behavior is that if a template, including ones with the embedded templates component, allows PUD, it's selected by default."  In the case of 2x2 Embedded Zoned, it allows it, so it's selected.  Right?

I don't know what the solution is, but the reason for logging this defect is that the user experience is not consistent if they embed a presentation that doesn't allow PUD into one that does.

Currently, it's possible for a user to select Play Until Done and have their content not play until done, which will create confusion and cause touches.

**Comment by olegrise** [comment] 2020-06-11 13:16
@PatrickA-RiseVision can we close this issue?

**Comment by PatrickA-RiseVision** [comment] 2020-06-11 14:08
@olegrise if it's being tracked elsewhere I'm ok with closing it.

**Comment by olegrise** [comment] 2020-06-11 14:13
@alanclayton are you going to make a note of this feature request somewhere? Thanks.

**Comment by alanclayton** [comment] 2020-06-11 15:41
@olegrise Correct. You can close.

**Closed** 2020-06-11 15:47 UTC
