### ISSUE TITLE
Presentation title saved incorrectly in Samsung Galaxy S8 Chrome

### ISSUE THREAD

**Issue by santiagonoguez** [Rise-Vision/rise-vision-apps#1074] opened 2019-06-24 16:58 UTC
This may be related to https://github.com/Rise-Vision/rise-vision-apps/issues/1073

When editing title in an HTML template presentation in Chrome / Samsung Galaxy S8, the auto-save is invoked before editing finishes, and in some cases it doesn't pick the latest changes written. For example I appended some words to the title, but the saved presentation only contains some of them ( up to the auto-save ). The rest of them are not saved, and the presentation does not detect there were changes.

**Comment by santiagonoguez** [comment] 2019-06-26 18:44
I've also seen this now in Desktop Chrome, so it's not an issue exclusive to Samsung Galaxy Chrome

**Comment by andrecardoso** [comment] 2019-07-18 18:34
I can't find a way to reproduce this. Closing it for now.

**Closed by andrecardoso** 2019-07-18 18:34 UTC

**Comment by fjvallarino** [comment] 2019-07-18 18:42
@andrecardoso I could not reproduce it either. I agree with closing the issue.
