### ISSUE TITLE
Opening a Draft HTML Template and attempting to navigate away Publishes Template

### ISSUE THREAD

**Issue by alex-deaconu** [Rise-Vision/rise-vision-apps#1186] opened 2019-08-15 17:39 UTC
To replicate:
Go to Presentations list (refresh the page just in case).
Navigate to a draft template
Click the Presentations link in the Common Header

What happens:
The page doesn't navigate to the Presentations page
The Template gets Published

https://screencast.com/t/jtkDR9dRqkV7

Not sure if this is desired behaviour, but I found it quite surprising.

First off, the navigation does NOT work.
Second, the Template gets published without me clicking the Publish button.

Thanks!

**Comment by santiagonoguez** [comment] 2019-08-16 13:51
@alex-deaconu HTML presentations always get published when first opened. That's because Core always publishes when a presentation is first saved. With auto-save, if we wait for the first change of the user, this means we would be publishing a presentation in a potentially broken state; so we prefered to save/publish immediately so it's at least published in a default state. To 'fix' this would require the behavior at Core, which we did not want to change at the time this was implemented.

@stulees @fjvallarino @sheadarlison

**Comment by santiagonoguez** [comment] 2019-08-16 13:56
BTW, the design doc for this is here: https://docs.google.com/document/d/1KqmqzQWJ0nqVsYJu0Fysl5q27mW-VowMQ7AFHxFMfjo/edit#heading=h.muv6fbam20lp

**Comment by alex-deaconu** [comment] 2019-08-16 17:51
@santiagonoguez I understand the Core limitations and the design for first save. However, this is an existing Presentation. It has been saved, published, and updated multiple times. First off, the navigation does NOT work which I found quite annoying and don't believe is expected behaviour. And it gets published without me doing anything specific is quite worrying because this means a client or Rise admin trying to preview content in the editor (which is what I was doing) would inadvertently make changes to the Display. Basically, I am terrified of previewing anything because of Autosave and now this Auto Publish. If both of those are features/intended behaviour they are certainly not documented in the link you posted. Thanks.

**Comment by santiagonoguez** [comment] 2019-08-16 17:54
@alex-deaconu if it's auto-publishing on an existing presentation, then this is certainly unintended behavior, thanks !

**Comment by fjvallarino** [comment] 2019-08-19 21:20
@alex-deaconu @santiagonoguez related to this discussion, the reason why the first time you create a presentation you can't navigate away is explained here: https://github.com/Rise-Vision/rise-vision-apps/pull/1091

This is the document where the proposal for the delayed Auto Schedule modal came from: https://docs.google.com/document/d/1M3onNFEQlXvxsfvOVNeIEsRJVK2JTZ2XBzJbmMWPa1M/edit#heading=h.vc9zna8j2910

Thanks!

**Comment by fjvallarino** [comment] 2019-08-19 21:25
@alex-deaconu @santiagonoguez just to clarify: Auto Publish is done by Core the first time a Presentation is saved (i.e., it is created). After that, Publish should only happen if the user clicked on Published.

**Comment by santiagonoguez** [comment] 2019-09-03 15:04
This has been fixed, and deployed to production. Closing this issue.

**Closed by santiagonoguez** 2019-09-03 15:04 UTC
