### ISSUE TITLE
Editing presentations on mobile

### ISSUE THREAD

**Issue by sheadarlison** [Rise-Vision/rise-vision-apps#259] opened 2016-09-28 19:08 UTC
**Presentation URL:**
https://apps.risevision.com/editor/workspace/c2312d8d-98bf-4246-92dd-7a57c09204f3/true?cid=f114ad26-949d-44b4-87e9-8528afc76ce4

**What is not working/What is currently happening:**
When I try to edit this presentation on mobile every time I click the placeholder area and not a button the side navigation pops out which makes it very difficult to use. And sometimes when I click buttons the side navigation pops out. 

**What is expected to work/What is the client expecting:**
If I accidentally click an area the side navigation does not popout

**What has been tried so far:**
Nothing

**Device** 
Nexus 6x

**Comment by ezequielc** [comment] 2016-09-28 19:17
@ghislaineguerin This is caused by the swipe gesture to open the side navigation. Do you think people use it or would it be ok to just remove the gesture detection? We can still access the navigation using the sandwich button. Thoughts? Thanks

**Comment by ezequielc** [comment] 2016-09-29 14:23
This issue will be addressed in future Editor improvements work. Closing it for now. Thanks

**Closed by ezequielc** 2016-09-29 14:23 UTC
