### ISSUE TITLE
Storage shows missing subscription for new users

### ISSUE THREAD

**Issue by tejohnso** [Rise-Vision/rise-vision-apps#1323] opened 2019-10-24 13:41 UTC
Create a new user, go directly to Storage tab. You'll see the contents indicating a subscription is required even though the top bar indicates trial has 14 days remaining.

**Comment by alex-deaconu** [comment] 2019-11-06 15:24
This issue is caused by latency between Adding a Company and Starting a Trial and that result not being available in the Store and the Subscription Status API (ie. unsubscribed would be returned).

To confirm, we tried fixing by starting the Trial on the server side. While this speeded things up somewhat the issue would still occur because the latency is still there (~7-10s).

We've implemented another fix, to inherit the Plan Subscription Status for Storage. This is based on the assumption that if they have a Plan they automatically have Storage, which is currently true (if that ever changes we would need to revise this). And when registering we hardcode the Plan Trial so it is immediately available on the client side.

However, the Storage Server will not allow bucket creation and file upload until it receives the Authorization from the Store, so despite the UI messaging being accurate, these actions will not be available until the webhook calls occur.

Closing. Thanks.

**Closed by alex-deaconu** 2019-11-06 15:24 UTC
