### ISSUE TITLE
Multiples of Same Presentation being Saved

### ISSUE THREAD

**Issue by mmeiers** [Rise-Vision/rise-vision-apps#1672] opened 2020-05-06 15:57 UTC
Steps to replicate
Create a new presentation from a Template in apps stage 0. Make changes to a text component size or rename the presentation. 

Expected outcome
I would expect it to only save that presentation when I publish or it autosaves.

Actual Outcome
The editor will save several versions of the same presentations with incremental changes that were made to the component or renaming of the presentation. This only happens periodically. Rowan has had it happened to her a couple of time and I have seen it 4-5 times now.

https://apps-stage-0.risevision.com/editor/list?cid=b428b4e8-c8b9-41d5-8a10-b4193c789443 See "Copy of Recycling" Template

**Comment by alex-deaconu** [comment] 2020-05-13 20:11
@mmeiers a fix has been deployed for this. This was caused by latency and/or slow API responses when adding the Template.

We have optimized the code so the Template is added before the page navigates which means this issue should no longer occur, and an overall better user experience when adding a Template.

Closing. Thanks!

**Closed by alex-deaconu** 2020-05-13 20:11 UTC
