### ISSUE TITLE
[Shared Schedules] Shared Schedule Has Missing Playlist Items

### ISSUE THREAD

**Issue by jasoncaldwell** [Rise-Vision/rise-vision-apps#2477] opened 2021-03-18 16:19 UTC
**Issue:** When I access my shared schedule via URL, there's a missing playlist item in my shared schedule. It's worth noting that the schedule shows all the playlist items on my display.

https://www.loom.com/share/3578a3536f274827a91280b5fd7ea7fd

**Expected behavior:** My shared schedule doesn't have a missing playlist item.

**Comment by ezequielc** [comment] 2021-03-18 16:31
@jasoncaldwell The item that is skipped is a Presentation that has unsupported content for Shared Schedules.
Twitter Widget only works on displays, I believe due to authentication limitations.

Reference: https://github.com/Rise-Vision/viewer/blob/54fdd7e5b7953942c6125ade7836ffef297fa154/src-js/Viewer/Data/ViewerDataInfo.js#L13

In summary, this is working as intended, even though not great for users. Thanks!

@alanclayton @alex-deaconu  fyi

**Comment by jasoncaldwell** [comment] 2021-03-18 17:27
@ezequielc Copy that, thanks for the context!

**Comment by ezequielc** [comment] 2021-03-18 17:33
@jasoncaldwell @alanclayton I am closing this, given the above. Thanks!

**Closed by ezequielc** 2021-03-18 17:33 UTC
Labels: bug
