### ISSUE TITLE
Attribute data is not populated properly

### ISSUE THREAD

**Issue by alexey-rise** [Rise-Vision/rise-vision-apps#1563] opened 2020-03-04 14:37 UTC
HTML Template https://apps.risevision.com/templates/edit/647a6522-1866-4b82-b7b7-663d856f77e2/?cid=b918f23b-c227-454a-8117-ca6bafe753d3 has 4 components (1 editable and 3 non editable):

![image](https://user-images.githubusercontent.com/7119180/75889702-51df8900-5dfb-11ea-8142-ff87576aa047.png)

However only 1 component (the first one) is present in the attribute data:

![image](https://user-images.githubusercontent.com/7119180/75889808-73d90b80-5dfb-11ea-8934-d6497a4a0d33.png)

The values for all 4 components should be present in the attribute data.

The issue *does not* appear to be limited to non-editable components only as it was reproduced earlier by Matt with a presentation where all components were editable.

**Comment by ezequielc** [comment] 2020-03-04 14:58
@alexey-rise @mmeiers Do you have an example of this issue where the components are not _non-editable_?
In the example above, as they are non-editable, it is the expected behaviour to not populate them and not list them in the Template Editor UI.

Another thing to notice is that even if you change the element to be editable in the template, you also need to regenerate the _blueprint.json_ to reflect that. Otherwise Template Editor will still assume they are non-editable. Thanks!

**Comment by alexey-rise** [comment] 2020-03-04 15:08
@ezequielc I believe the issue occurs when the new template is added initially.

While I agree that there is no need to list non-editable components in the editor, I don't agree that they shouldn't be populated in the **attribute-data.json**

Core uses **attribute-data.json** to display CAP Alerts in a Template (please read the full description here: https://docs.google.com/document/d/1lddFpeAHywu4T0uV4iupSZCqI1AOIEW8X-MdoGq69u8/edit?usp=sharing). Core does not expect the behavior to be different for non-editable components.

**Comment by ezequielc** [comment] 2020-03-04 15:35
@alexey-rise My understanding of _non-editable_ component is that it will have its values defined by the designer when creating the template initially. Even if we add to `attribute-data.json`, I am not sure if common-template is going to read those values and set to the elements.
Do we really want these elements to be non-editable if we want to set values to them? Thanks!

**Comment by tejohnso** [comment] 2020-03-05 14:47
It sounds to me like we are conflating two separate properties:

1. Whether the item is editable or not
2. Whether the item has dynamic attribute data

I don't think we should (any longer) assume that just because a component is not editable, it means it does not have any dynamic attribute data.

@ezequielc can we consider making the changes necessary to support this? Maybe another element property that common-template can look for? If this is something we need to do, can you point us in the right direction?

@alexey-rise @ezequielc @andrecardoso Can you think of any alternatives that aren't too hackish that don't use the *attribute-data.json* method? Personally, I think this method is the correct one. We just have to make a small change.

**Comment by mmeiers** [comment] 2020-03-05 15:12
@ezequielc @alexey-rise Here is an example of an editable version. There is an issue with them being editable when you first add the Template. You can't just publish the template and have it work. You have to phsyically click on each field for it to then save the values. It confuses me why we'd have to do that as they are already the default values.

You can see this by adding the template
https://apps.risevision.com/editor/add/cap-alert_v1
(Note this template is only visible through cid=b918f23b-c227-454a-8117-ca6bafe753d3)

https://apps.risevision.com/templates/edit/efdf467c-b399-409e-80aa-a6b8b220295d/?cid=b918f23b-c227-454a-8117-ca6bafe753d3

@alexey-rise Is there a requirement these have to be rise-text components. The legacy version fo this Template just had these as regular non-editable HTML. 
Example:
<div id="headline" class="text">%HEADLINE%</div>

This is what prompted me to make them non-editable in the first place along with the issue stated above. I'm just trying to directly replicate it. If making them editable makes fixing this easier we can consider it but right now I see issues with both ways.

**Comment by tejohnso** [comment] 2020-03-05 15:21
Couldn't the user end up changing them and breaking the alert functionality if they're editable?

**Comment by mmeiers** [comment] 2020-03-05 15:32
@tejohnso Yes ideally they cant edit or break this. Which circles back to my question above, is there a requirement that these must be rise-text components or can we do this similarly to the old Template and have Alerts target a value within an HTML Tag. `<div id="headline" class="text">%HEADLINE%</div>`

**Comment by alexey-rise** [comment] 2020-03-05 15:36
@mmeiers yes these must be components (doesn't have to be specifically rise-text, it just needs to be something that displays text data). We can't do this the way old Presentation used to work and have the tokens inside the HTML because the HTML is no longer stored on the server (whereas attribute data is).

**Comment by ezequielc** [comment] 2020-03-05 16:13
@tejohnso @alexey-rise,  @alex-deaconu's suggestion is that Core should follow what Template Editor does. It checks the blueprint.json for the appropriate components and updates the attribute-data.json accordingly. 
I think it is a good approach as it would be a consistent flow across the implementations. Thanks

**Comment by alexey-rise** [comment] 2020-03-05 16:20
@ezequielc could you clarify this recommendation? At what point is the Core supposed to check blueprint.json and update the attribute-data.json? My understanding is that this is done by Apps.

**Comment by tejohnso** [comment] 2020-03-05 16:24
> @tejohnso @alexey-rise, @alex-deaconu's suggestion is that Core should follow what Template Editor does. It checks the blueprint.json for the appropriate components and updates the attribute-data.json accordingly.
> I think it is a good approach as it would be a consistent flow across the implementations. Thanks

Is the template, when loaded at runtime, going to populate the values though? I thought the issue was that the atribute-data values aren't going to get populated for non editable components, even if Core has updated the attribute-data.json.

**Comment by tejohnso** [comment] 2020-03-05 18:27
@ezequielc @alexey-rise @alex-deaconu We spoke...we're going to implement a server side improvement to take blueprint.json into account and you're going to verify that non-editable components will load attribute-data and correct if required.

**Comment by alex-deaconu** [comment] 2020-03-09 17:15
@alexey-rise to confirm, the fix that we discussed is now deployed.

So, non editable components will receive data from attribute-data.json. This has been validated both in the Editor and on Displays. 

Let me know when this is ready to be closed. Thanks!

**Comment by alex-deaconu** [comment] 2020-03-12 13:46
@alexey-rise closing this, as I believe all the code changes for the fix have been deployed. Creative can re-open if they have further issues. Thanks!

**Closed by alex-deaconu** 2020-03-12 13:46 UTC
