### ISSUE TITLE
Text widget loads very slowly / unreliably

### ISSUE THREAD

**Issue by PatrickA-RiseVision** [Rise-Vision/rise-vision-apps#2471] opened 2021-03-08 17:08 UTC
### What is the expected behavior?
When you click on the widget to edit it, it loads.

### What is the actual behavior?
When opening the text widget to edit, load times are significantly longer than you'd expect regardless of whether there is text.
In some cases it doesn't seem to load at all, even if you wait, until you try to navigate to a different tab in Chrome which sometimes causes it to refresh and load.

### What steps can be taken to replicate the problem?
1. Create a presentation from blank
2. Add a placeholder
3. Add the text widget
4. Wait for it to load or not load, it's kind of a crapshoot

**Comment by ezequielc** [comment] 2021-03-08 17:10
@stulees @olegrise fyi. I think you should grab this. Thanks

**Comment by stulees** [comment] 2021-03-08 17:22
@PatrickA-RiseVision I can't reproduce this. Can you provide any additional details on how you reproduce this and/or share a video? Thanks

**Comment by PatrickA-RiseVision** [comment] 2021-03-08 20:06
@stulees I can't replicate it anymore, and nor can the user.  We both had the problem at the same time, and then we both suddenly had it working at the same time.  It's got me wondering if it's some network or server resource that was required and struggling at the time the user and I were both trying.

I did manage to get it to load pretty slowly while recording this video for you: https://drive.google.com/file/d/1Askh3sMGqmIQ90gade1okqQhB7nOZKPT/view?usp=drivesdk but it's nowhere near the amount of time it took this morning.

@jasoncaldwell will hopefully attest that I'm not just crazy since I was screen sharing with him when I logged the defect.  I just wish I knew more about the cause so we could replicate it reliably.

**Comment by stulees** [comment] 2021-03-08 20:10
@PatrickA-RiseVision Okay thanks. If this can't be replicated any further, I recommend we close the issue. Do you agree? @olegrise FYI

**Comment by jasoncaldwell** [comment] 2021-03-08 20:15
While on the call with @PatrickA-RiseVision, I can confirm that the text input for the text widget wasn't loading at all for the customer.

**Comment by PatrickA-RiseVision** [comment] 2021-03-08 20:28
@stulees Yes, feel free to close.  If it happens again we can always reopen.

**Closed** 2021-03-08 20:32 UTC
